//functions 
//function for display cricket news
function displayNewsData(data){
    data.forEach(function(ele){
        let p2=document.createElement("p")
        p2.setAttribute("class","p2")
        p2.innerText=ele.p2
        let p3=document.createElement("p")
        p3.setAttribute("class","p3")
        p3.innerText=ele.p3
        let hr=document.createElement("hr")
        hr.setAttribute("class","line")
        document.querySelector("#append_data").append(p2,p3,hr)
    });
}

//function for display latest photo
function displayPhotoData(data){
    data.forEach(function(ele){
         let news_div=document.createElement("div")
         news_div.setAttribute("class","news")
             let news_img=document.createElement("div")
             news_img.setAttribute("class","news_img")
                 let img=document.createElement("img")
                 img.setAttribute("src",ele.image)
            news_img.append(img)
             let news_text=document.createElement("div")
             news_text.setAttribute("class","news_text")
                let p5=document.createElement("p")
                p5.setAttribute("class","p5")
                p5.innerText=ele.p5
                let p4=document.createElement("p")
                p4.setAttribute("class","p4")
                p4.innerText=ele.p4
             news_text.append(p5,p4)
         let hr=document.createElement("hr")
         hr.setAttribute("class","line")

         news_div.append(news_img,news_text)
         document.querySelector("#append_data2").append(news_div,hr)
    });
}


let dataForPhoto=[
    {image:"https://www.cricbuzz.com/a/img/v1/100x77/i1/c236004/masood-fell-two-runs-short-of.jpg",p5:"Shan Masood 98 centrepiece of Derbyshire's thrilling win over Middlesex",p4:"1h ago"},
    {image:"https://www.cricbuzz.com/a/img/v1/100x77/i1/c236003/digital-india-drives-ipls-val.jpg",p5:"Space for two in the IPL rights pie",p4:"2h ago"},
    {image:"https://www.cricbuzz.com/a/img/v1/100x77/i1/c236002/maxwell-scored-80-of-the-93-ru.jpg",p5:"Maxwell blinder helps Australia scale tough chase",p4:"2h ago"},
    {image:"https://www.cricbuzz.com/a/img/v1/100x77/i1/c236000/lara-goodall-hit-93-off-99-to.jpg",p5:"Goodall, Steyn ace chase against improved Ireland",p4:"2h ago"},
    {image:"https://www.cricbuzz.com/a/img/v1/100x77/i1/c235996/noor-ahmad-picked-4-for-10-as.jpg",p5:"Noor Ahmad stars as Afghanistan clean-sweep T20I series",p4:"2h ago"},
    {image:"https://www.cricbuzz.com/a/img/v1/100x77/i1/c235999/india-won-the-third-t20i-by-48.jpg",p5:"South Africa learn that India don't go quietly",p4:"2h ago"}
    ]

    displayPhotoData(dataForPhoto)

let data=[
{p2:"IPL 2022",p3:"IPL 2022"},
{p2:"INSIDE STORY",p3:"Unpacking all the facts and going in-depth into news stories"},
{p2:"REFLECTIONS",p3:"A deep and considered look at relevant themes"},
{p2:"DIALOGUE ROOM",p3:"A new, in-depth interview with people who matter"},
{p2:"THINK TANK",p3:"Deconstructing the finer nuances of the game"},
{p2:"IPL 2020 PREVIEWS",p3:"Building up to IPL 2020 with an exhaustive analysis of all the eight teams in contention"},
{p2:"VIEW-COUNTERVIEW",p3:"Debating, dissecting and inviting opinions on the two opposing sides to all things cricket"},
{p2:"THE NAME OF THE GAME",p3:"An exclusive series where our team of writers, alongside experts, break down the art and science of cricket."},
{p2:"THE FIRST DAY OF THE REST OF THEIR LIVES",p3:"Retirement talks and more..."},
{p2:"ONCE UPON AN IPL FINAL",p3:"Young cricketers recount their memories from IPL final, the drama building up to the big match and the events after it"},
{p2:"THE IPL BENCHWARMERS",p3:"We talk to players who made it to the IPL alright, but didn't go very far, and were out of opportunities - and reckoning - sooner than they'd have liked"},
{p2:"COVID-19 & CRICKET",p3:"COVID-19 & Cricket"},
{p2:"DECADE-END SPECIALS",p3:"Decade-end specials"},
{p2:"WORLD CUP SUBCULTURE",p3:"World Cup Subculture"},
{p2:"WORLD CUP 2019: THE READY RECKONERS",p3:"World Cup 2019: The Ready Reckoners"},
{p2:"WORLD CUP 2019: THE SPECIAL ONE",p3:"World Cup 2019: The Special One"},
{p2:"WORLD CUP FLASHBACK",p3:"Revisiting some of the memorable moments in World Cup history"},
{p2:"WORLD CUP 2019 SQUADS",p3:"World Cup 2019 Squads"},
{p2:"THE T20 REVOLUTION",
p3:"Trista Holme, Bharat Sunderasan, Ahsan Iftikhar Nagi, Barny Read"},
{p2:"IPL 2019 PREVIEWS",
p3:"Cricbuzz Staff"},
{p2:"2018 - A YEAR IN REVIEW",
p3:"What went right, and wrong, for the teams, the best teams of the year and more"},
{p2:"IPL 2019 AUCTION",
p3:"All stories, news and analysis surrounding the 2019 IPL auction"},
{p2:"IPL 2019",
p3:"All the squads and other news stories relating to the Indian Premier League 2019"},
{p2:"NEWLANDS BALL TAMPERING SAGA",
p3:"Cameron Bancroft and Australia skipper Steven Smith confessed to pre-meditating the act of altering the condition of the ball during the third Test"},
{p2:"IPL 2018 - AUCTION AND RETENTION",
p3:"News and updates for the grand auction ahead of Indian Premier League's 11th edition"},
{p2:"2017 - YEAR IN REVIEW",
p3:"A look back at the teams and their fortunes over the latest 12-month cycle"},
{p2:"BEN STOKES'S BRISTOL BRAWL",
p3:"Ben Stokes finds himself in trouble and facing a possible Ashes axe after a drunken brawl that led to a fractured finger and his arrest"},
{p2:"CHAMPIONS TROPHY REVIEWS",
p3:"A team-by-team review, among other things, of the Champions Trophy 2017"},
{p2:"IPL 2017 - OFF THE CUFF",
p3:"Fun interviews with IPL 2017 cricketers"},
{p2:"IPL 2017 - TEAM PREVIEWS AND BUILDUP",
p3:"Indian Premier League, 2017 - Team Previews and Buildup"},
{p2:"REVIEWGATE CONTROVERSY",
p3:"Reviewgate Controversy, India vs Australia, Test series"},
{p2:"IPL AUCTIONS 2017",
p3:"Indian Premier League Auctions, 2017"},
{p2:"MS DHONI STEPS DOWN AS CAPTAIN",
p3:"MS Dhoni steps down as captain from limited-overs cricket"},
{p2:"2016 - THE YEAR IN REVIEW",
p3:"What was best about 2016, and what was bad about it - all in one section"},
{p2:"RANJI TROPHY KNOCK-OUT STAGES: ANALYSIS, FEATURES & INTERVIEWS",
p3:"Digging deep to bring you all the analysis from India's premier domestic tournament"},
{p2:"ICC AWARDS",
p3:"All the news from the International Cricket Council's annual awards - the time frame was from September 2015 to September 2016"},
{p2:"FAF DU PLESSIS BALL-TAMPERING CONTROVERSY",
p3:"The South African Test captain was caught on camera, applying saliva to the ball with a lolly in his mouth. Controversy erupted"},
{p2:"AUSTRALIA CRICKET CRISIS",
p3:"Australia lost fiec consecutive Test matches in 2016 and several pundits termed it a crisis while calling for a shake-up of Australian cricket to fix it."},
{p2:"WORLD T20 '16 - TEAM SWOT",
p3:"World T20 '16 - Team SWOT"},
{p2:"SWITCH HIT WITH SEHWAG",
p3:"Switch hit with Sehwag"},
{p2:"THAT HAPPENED",
p3:"That Happened"},
{p2:"2015 - THE YEAR IN REVIEW",
p3:"2015 - The year in review"},
{p2:"ROAD TO IPL 2016",
p3:"New Teams, Player Auctions and more."},
{p2:"VIRENDER SEHWAG RETIREMENT",
p3:"Virender Sehwag retirement"},
{p2:"CHRIS CAIRNS PERJURY TRIAL",
p3:"Chris Cairns Perjury trial"},
{p2:"INDIA VS SOUTH AFRICA: INTERVIEWS",
p3:"India vs South Africa: Interviews"},
{p2:"INDIA VS SOUTH AFRICA, 2015: SPECIALS",
p3:"India vs South Africa, 2015: Specials"},
{p2:"KUMAR SANGAKKARA FAREWELL",
p3:"Kumar Sangakkara farewell"},
{p2:"KARNATAKA PREMIER LEAGUE 2015",
p3:"Karnataka Premier League 2015"},
{p2:"IPL BETTING SCAM VERDICT",
p3:"IPL Betting scam verdict"},
{p2:"ZIMBABWE'S TOUR OF PAKISTAN",
p3:"Zimbabwe's tour of Pakistan"},
{p2:"IPL 2015: TEAM PREVIEWS",
p3:"IPL 2015: Team Previews"},
{p2:"WORLD CUP TEAM REVIEWS",
p3:"World Cup Team Reviews"},
{p2:"BCCI ELECTIONS 2015",
p3:"BCCI elections 2015"},
{p2:"CRICBUZZ AT THE WORLD CUP",
p3:"Cricbuzz at the World Cup"},
{p2:"WC 2015 - WHAT TO LOOK FORWARD TO",
p3:"WC 2015 - What to look forward to"},
{p2:"IPL 2015",
p3:"IPL 2015"},
{p2:"50 FASCINATING FACTS ABOUT WORLD CUPS",
p3:"50 fascinating facts about World Cups"},
{p2:"WORLD CUP TEAM PREVIEWS",
p3:"World Cup team previews"},
{p2:"ICC WORLD CUP 2015 - EXPERTS' CORNER",
p3:"ICC World Cup 2015 - Experts' Corner"},
{p2:"AUSTRALIA TRI-SERIES 2014-15",
p3:"Australia tri-series 2014-15"},
{p2:"RANJI TROPHY 2014-15",
p3:"Ranji Trophy 2014-15"},
{p2:"WORLD CUP 2015 - FINAL SQUADS",
p3:"World Cup 2015 - Final Squads"},
{p2:"BEST TEAM TO NOT WIN THE WORLD CUP",
p3:"Best team to not win the World Cup"},
{p2:"WORLD CUP HEROES",
p3:"World Cup Heroes"},
{p2:"2014 - A YEAR IN REVIEW",
p3:"2014 - A year in review"},
{p2:"DHONI TEST RETIREMENT",
p3:"Dhoni Test retirement"},
{p2:"COUNTDOWN TO ICC CRICKET WORLD CUP, 2015",
p3:"Countdown to ICC Cricket World Cup, 2015"},
{p2:"ICC CRICKET WORLD CUP, 2015 - PROBABLES",
p3:"ICC Cricket World Cup, 2015 - Probables"},
{p2:"RIP PHILLIP HUGHES",
p3:"RIP Phillip Hughes"},
{p2:"INDIA TOUR OF AUSTRALIA, 2014-15",
p3:"India tour of Australia, 2014-15"},
{p2:"SACHIN TENDULKAR AUTOBIOGRAPHY",
p3:"Sachin Tendulkar Autobiography"},
{p2:"SRI LANKA IN INDIA, 2014",
p3:"Sri Lanka in India, 2014"},
{p2:"ICC CRICKET WORLD CUP 2015",
p3:"ICC Cricket World Cup 2015"},
{p2:"SOUTH AFRICA IN NEW ZEALAND, 2014",
p3:"South Africa in New Zealand, 2014"},
{p2:"WEST INDIES' INDIA TOUR PULL-OUT",
p3:"West Indies' India tour pull-out"},
{p2:"KP: THE AUTOBIOGRAPHY",
p3:"KP: The Autobiography"},
{p2:"BANGLADESH TOUR OF WEST INDIES, 2014",
p3:"Bangladesh tour of West Indies, 2014"},
{p2:"SAEED AJMAL SUSPENDED FOR CHUCKING",
p3:"Saeed Ajmal suspended for chucking"},
{p2:"PAKISTAN V AUSTRALIA IN UAE, 2014",
p3:"Pakistan v Australia in UAE, 2014"},
{p2:"FORMER CRICKETERS CRITICISE ALASTAIR COOK",
p3:"Former cricketers criticise Alastair Cook"},
{p2:"ZIMBABWE TRIANGULAR SERIES, 2014",
p3:"Zimbabwe Triangular Series, 2014"},
{p2:"CHAMPIONS LEAGUE T20 2014",
p3:"Champions League T20 2014"},
{p2:"WEST INDIES TOUR OF INDIA, 2014",
p3:"West Indies tour of India, 2014"},
{p2:"MAHELA JAYWARDENE TEST RETIREMENT",
p3:"Mahela Jaywardene Test retirement"},
{p2:"SOUTH AFRICA IN ZIMBABWE, 2014",
p3:"South Africa in Zimbabwe, 2014"},
{p2:"PAKISTAN TOUR OF SRI LANKA, 2014",
p3:"Pakistan tour of Sri Lanka, 2014"},
{p2:"JIMMY ANDERSON-RAVINDRA JADEJA SPAT",
p3:"Anderson-Jadeja spat"},
{p2:"SOUTH AFRICA TOUR OF SRI LANKA, 2014",
p3:"South Africa tour of Sri Lanka, 2014"},
{p2:"INDIA TOUR OF ENGLAND, 2014",
p3:"India tour of England, 2014"},
{p2:"NEW ZEALAND TOUR OF WEST INDIES, 2014",
p3:"New Zealand tour of West Indies, 2014"},
{p2:"INDIA TOUR OF BANGLADESH, 2014",
p3:"India tour of Bangladesh, 2014"},
{p2:"MATCH-FIXING SAGA 2013-14",
p3:"Match-fixing saga 2013-14"},
{p2:"SRI LANKA TOUR OF ENGLAND AND IRELAND, 2014",
p3:"Sri Lanka tour of England and Ireland, 2014"},
{p2:"PEPSI INDIAN PREMIER LEAGUE 2014",
p3:"Pepsi Indian Premier League 2014"},
{p2:"IPL 2013: SPOT FIXING CONTROVERSY",
p3:"IPL 2013: Spot fixing controversy"},
{p2:"WORLD T20, 2014",
p3:"World T20, 2014"},
{p2:"ICC T20 WORLD CUP, 2014",
p3:"ICC T20 World Cup, 2014"},
{p2:"ENGLAND IN WEST INDIES 2014",
p3:"England in West Indies 2014"},
{p2:"U-19 WORLD CUP, 2014",
p3:"U-19 World Cup, 2014"},
{p2:"AUSTRALIA TOUR OF SA 2014",
p3:"Australia tour of SA 2014"},
{p2:"ASIA CUP 2014",
p3:"Asia Cup 2014"},
{p2:"ICC REVAMP",
p3:"ICC Revamp"},
{p2:"INDIA TOUR OF NEW ZEALAND, 2014",
p3:"India tour of New Zealand, 2014"},
{p2:"ENGLAND IN AUSTRALIA, 2014",
p3:"ODI Series"},
{p2:"PAKISTAN VS SRI LANKA IN UAE, 2013/14",
p3:"Pakistan vs Sri Lanka in UAE, 2013/14"},
{p2:"INDIA IN SOUTH AFRICA, 2013",
p3:"India in South Africa, 2013"},
{p2:"WEST INDIES IN INDIA, 2013",
p3:"West Indies in India, 2013"},
{p2:"PAKISTAN V SOUTH AFRICA IN UAE, 2013",
p3:"Pakistan v South Africa in UAE, 2013"},
{p2:"SACHIN TENDULKAR TEST RETIREMENT",
p3:"Sachin Tendulkar Test retirement"},
{p2:"AUSTRALIA'S LIMITED OVERS TOUR OF INDIA, 2013",
p3:"Australia's limited overs tour of India, 2013"},
{p2:"ENGLAND IN AUSTRALIA, 2013/14",
p3:"England in Australia, 2013/14"},
{p2:"CHAMPIONS LEAGUE T20, 2013",
p3:"Champions League T20, 2013"},
{p2:"INDIA IN ZIMBABWE, 2013",
p3:"India in Zimbabwe, 2013"},
{p2:"ASHES 2013 - AUSTRALIA IN ENGLAND",
p3:"Ashes 2013 - Australia in England"},
{p2:"INDIA AND SRI LANKA IN WEST INDIES - TRI-SERIES 2013",
p3:"India and Sri Lanka in West Indies - Tri-Series 2013"},
{p2:"NEW ZEALAND TOUR OF ENGLAND 2013",
p3:"New Zealand tour of England 2013"},
{p2:"CHAMPIONS TROPHY 2013",
p3:"Champions Trophy 2013"},
{p2:"CRICBUZZ REWIND",
p3:"Cricbuzz Rewind"},
{p2:"RYDER'S BAR BRAWL",
p3:"Ryder's bar brawl"},
{p2:"INDIAN PREMIER LEAGUE, 2013",
p3:"Indian Premier League, 2013"},
{p2:"ZIMBABWE IN WEST INDIES, 2013",
p3:"Zimbabwe in West Indies, 2013"},
{p2:"BANGLADESH IN SRI LANKA, 2013",
p3:"Bangladesh in Sri Lanka, 2013"},
{p2:"ENGLAND IN NEW ZEALAND, 2013",
p3:"England in New Zealand, 2013"},
{p2:"WOMEN'S WORLD CUP, 2013",
p3:"Women's World Cup, 2013"},
{p2:"PAKISTAN IN SOUTH AFRICA, 2013",
p3:"Pakistan in South Africa, 2013"},
{p2:"WEST INDIES IN AUSTRALIA, 2013",
p3:"West Indies in Australia, 2013"},
{p2:"AUSTRALIA TOUR OF INDIA 2013",
p3:"Australia tour of India 2013"},
{p2:"TONY GREIG'S DEATH",
p3:"Tony Greig's death"},
{p2:"SACHIN TENDULKAR ODI RETIREMENT: SPECIALS",
p3:"Sachin Tendulkar ODI retirement: Specials"},
{p2:"SACHIN TENDULKAR ODI RETIREMENT",
p3:"Sachin Tendulkar ODI retirement"},
{p2:"YEAR IN REVIEW, 2012",
p3:"Year in Review, 2012"},
{p2:"NEW ZEALAND IN SOUTH AFRICA, 2012-13",
p3:"New Zealand in South Africa, 2012-13"},
{p2:"BIG BASH LEAGUE 2012-13",
p3:"Big Bash League 2012-13"},
{p2:"SRI LANKA IN AUSTRALIA, 2012 - 13",
p3:"Sri Lanka in Australia, 2012 - 13"},
{p2:"PAKISTAN TOUR OF INDIA, 2012 - 13",
p3:"Pakistan tour of India, 2012 - 13"},
{p2:"RICKY PONTING RETIREMENT",
p3:"Ricky Ponting retirement"},
{p2:"WEST INDIES TOUR OF BANGLADESH 2012",
p3:"West Indies tour of Bangladesh 2012"},
{p2:"RANJI TROPHY CONTENDERS - TEAM PROFILES",
p3:"Ranji Trophy Contenders - Team Profiles"},
{p2:"ENGLAND IN INDIA, 2012 - 13",
p3:"England in India, 2012 - 13"},
{p2:"DECCAN CHARGERS' EJECTION FROM IPL",
p3:"Deccan Chargers' ejection from IPL"},
{p2:"NEW ZEALAND IN SRI LANKA, 2012",
p3:"New Zealand in Sri Lanka, 2012"},
{p2:"SOUTH AFRICA IN AUSTRALIA, 2012",
p3:"South Africa in Australia, 2012"},
{p2:"RANJI TROPHY, 2012",
p3:"Ranji Trophy, 2012"},
{p2:"CHAMPIONS LEAGUE T20, 2012",
p3:"Champions League T20, 2012"},
{p2:"ICC AWARDS, 2012",
p3:"ICC Awards, 2012"},
{p2:"NEW ZEALAND IN INDIA, 2012",
p3:"New Zealand in India, 2012"},
{p2:"PIETERSEN CONTROVERSY",
p3:"Pietersen Controversy"},
{p2:"SHAFI DARASHAH TOURNAMENT, 2012",
p3:"Shafi Darashah Tournament, 2012"},
{p2:"INDIA IN SRI LANKA, 2012",
p3:"India in Sri Lanka, 2012"},
{p2:"ICC WC T20, 2012 - PROVISIONAL SQUADS",
p3:"ICC WC T20, 2012 - Provisional Squads"},
{p2:"ICC WORLD T20, 2012 SQUADS",
p3:"ICC World T20, 2012 Squads"},
{p2:"ICC WORLD T20, 2012",
p3:"ICC World T20, 2012"},
{p2:"SOUTH AFRICA IN ENGLAND, 2012",
p3:"South Africa in England, 2012"},
{p2:"PIETERSEN RETIRES FROM LIMITED-OVERS CRICKET",
p3:"Pietersen retires from limited-overs cricket"},
{p2:"WEST INDIES IN ENGLAND, 2012",
p3:"West Indies in England, 2012"},
{p2:"IPL 2012 - TEAM PROFILES",
p3:"IPL 2012 - Team Profiles"},
{p2:"ENGLAND IN SRI LANKA 2012",
p3:"England in Sri Lanka 2012"},
{p2:"TENDULKAR TON OF TONS",
p3:"Tendulkar ton of tons"},
{p2:"AUSTRALIA'S TOUR OF THE WEST INDIES, 2012",
p3:"Australia's tour of the West Indies, 2012"},
{p2:"RAHUL DRAVID RETIREMENT SPECIALS",
p3:"Rahul Dravid retirement specials"},
{p2:"RAHUL DRAVID RETIREMENT",
p3:"Rahul Dravid retirement"},
{p2:"ASIA CUP, 2012",
p3:"Asia Cup, 2012"},
{p2:"SOUTH AFRICA'S TOUR OF NEW ZEALAND, 2012",
p3:"South Africa's tour of New Zealand, 2012"},
{p2:"SAHARA-BCCI STAND-OFF",
p3:"Sahara-BCCI stand-off"},
{p2:"IPL 2012",
p3:"IPL 2012"},
{p2:"CB SERIES 2012 - AUSTRALIA, INDIA, SRI LANKA",
p3:"CB Series 2012 - Australia, India, Sri Lanka"},
{p2:"ENGLAND IN PAKISTAN, 2012",
p3:"England in Pakistan, 2012"},
{p2:"YEAR IN REVIEW, 2011",
p3:"Year in review, 2011"},
{p2:"INDIA IN AUSTRALIA: SPECIALS",
p3:"India in Australia: Specials"},
{p2:"BIG BASH LEAGUE 2011",
p3:"Big Bash League 2011"},
{p2:"SEHWAG'S RECORD-BREAKING 219",
p3:"Sehwag's record-breaking 219"},
{p2:"SRI LANKA TOUR OF SOUTH AFRICA, 2011-12",
p3:"Sri Lanka tour of South Africa, 2011-12"},
{p2:"PAKISTAN IN BANGLADESH 2011",
p3:"Pakistan in Bangladesh 2011"},
{p2:"NEW ZEALAND IN AUSTRALIA, 2011",
p3:"New Zealand in Australia, 2011"},
{p2:"INDIA IN AUSTRALIA TEST SERIES, 2011-12",
p3:"India in Australia Test Series, 2011-12"},
{p2:"WEST INDIES IN INDIA, 2011",
p3:"West Indies in India, 2011"},
{p2:"ICC RELEASES T20 RANKINGS",
p3:"ICC releases T20 rankings"},
{p2:"NEW ZEALAND IN ZIMBABWE, 2011",
p3:"New Zealand in Zimbabwe, 2011"},
{p2:"SRI LANKA VS PAKISTAN, 2011",
p3:"Sri Lanka vs Pakistan, 2011"},
{p2:"WEST INDIES IN BANGLADESH, 2011",
p3:"West Indies in Bangladesh, 2011"},
{p2:"AUSTRALIA TOUR OF SOUTH AFRICA, 2011",
p3:"Australia tour of South Africa, 2011"},
{p2:"ENGLAND IN INDIA 2011",
p3:"England in India 2011"},
{p2:"SHOAIB AKTHAR'S AUTOBIOGRAPHY",
p3:"Shoaib Akthar's Autobiography"},
{p2:"MAK PATAUDI PASSES AWAY",
p3:"MAK Pataudi passes away"},
{p2:"BCCI AGM 2011",
p3:"BCCI AGM 2011"},
{p2:"DRAVID'S ODI RETIREMENT",
p3:"Dravid's ODI retirement"},
{p2:"ICC AWARDS 2011",
p3:"ICC Awards 2011"},
{p2:"CHAMPIONS LEAGUE T20, 2011",
p3:"Champions League T20, 2011"},
{p2:"2000TH TEST SPECIALS",
p3:"2000th Test Specials"},
{p2:"AUSTRALIA TOUR OF SRI LANKA, 2011",
p3:"Australia tour of Sri Lanka, 2011"},
{p2:"INDIA TOUR OF ENGLAND 2011",
p3:"India tour of England 2011"},
{p2:"SRI LANKA TOUR OF ENGLAND 2011",
p3:"Sri Lanka tour of England 2011"},
{p2:"INDIA TOUR OF WEST INDIES, 2011",
p3:"India tour of West Indies, 2011"},
{p2:"DUNCAN FLETCHER APPOINTED INDIA COACH",
p3:"Duncan Fletcher appointed India coach"},
]

displayNewsData(data)
